name: M-Mart+ Backend Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test Laravel Application
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: test_db
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, dom, fileinfo, mysql
          coverage: xdebug
      
      - name: Copy .env.example
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      
      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader
      
      - name: Generate key
        run: php artisan key:generate
      
      - name: Configure Database
        run: |
          php artisan config:clear
          php artisan migrate --force
          php artisan db:seed --force
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: test_db
          DB_USERNAME: root
          DB_PASSWORD: root
      
      - name: Run PHPUnit tests
        run: vendor/bin/phpunit
  
  deploy:
    name: Deploy to DigitalOcean
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DO_SSH_KEY }}
          known_hosts: ${{ secrets.DO_KNOWN_HOSTS }}
          config: |
            Host mmartplus-api
              HostName ${{ secrets.DO_HOST }}
              User ${{ secrets.DO_USER }}
              IdentityFile ~/.ssh/id_rsa
      
      - name: Deploy to Server
        run: |
          ssh mmartplus-api "cd /var/www/mmartplus && git pull origin main"
          ssh mmartplus-api "cd /var/www/mmartplus && composer install --no-dev --optimize-autoloader"
          ssh mmartplus-api "cd /var/www/mmartplus && php artisan migrate --force"
          ssh mmartplus-api "cd /var/www/mmartplus && php artisan config:cache"
          ssh mmartplus-api "cd /var/www/mmartplus && php artisan route:cache"
          ssh mmartplus-api "cd /var/www/mmartplus && php artisan view:cache"
          ssh mmartplus-api "sudo supervisorctl restart mmartplus-worker:*"
